### ISSUE TITLE
gp.se and www.gp.se

### ISSUE THREAD

**Issue by funilrys** [Ultimate-Hosts-Blacklist/whitelist#81] opened 2019-08-11 22:43 UTC
@denizdogan [said](https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/issues/518):
> This is the biggest newspaper in Gothenburg, Sweden and should not be blocked.

**Comment by dnmTX** [comment] 2019-08-12 01:00
Go ahead @funilrys,whitelist it.Looks like legitimate news site.

**Comment by dnmTX** [comment] 2019-08-13 00:28
@denizdogan confirmed and whitelisted. Thank you for you contribution.
Closing....

**Closed by dnmTX** 2019-08-13 00:28 UTC
Labels: whitelisting process
